/** Generated by xsd2c*/
#ifndef __generateRPMResponse_H__
#define __generateRPMResponse_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_GENERATERPMRESPONSE(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: generateRPMResponse
 */
struct generateRPMResponse
{
	int out;
};

/**
 *	LIST: generateRPMResponse_List
 */
struct generateRPMResponse_List
{
	struct generateRPMResponse* value;
	struct generateRPMResponse_List* next;
};


struct generateRPMResponse* generateRPMResponse_Create();
void generateRPMResponse_Free(struct generateRPMResponse* obj);
void generateRPMResponse_Sax_Serialize(struct generateRPMResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct generateRPMResponse* generateRPMResponse_Deserialize(xmlNodePtr xmlRoot);
#endif

void generateRPMResponse_Set_out(struct generateRPMResponse* obj, int out);
int generateRPMResponse_Get_out(struct generateRPMResponse* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
