/** Generated by xsd2c*/
#ifndef __generateRPM_H__
#define __generateRPM_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_GENERATERPM(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: generateRPM
 */
struct generateRPM
{
	char* in0;
};

/**
 *	LIST: generateRPM_List
 */
struct generateRPM_List
{
	struct generateRPM* value;
	struct generateRPM_List* next;
};


struct generateRPM* generateRPM_Create();
void generateRPM_Free(struct generateRPM* obj);
void generateRPM_Sax_Serialize(struct generateRPM* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct generateRPM* generateRPM_Deserialize(xmlNodePtr xmlRoot);
#endif

void generateRPM_Set_in0(struct generateRPM* obj, const char* in0);
char* generateRPM_Get_in0(struct generateRPM* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
