/** Generated by xsd2c*/
#ifndef __getError_H__
#define __getError_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_GETERROR(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: getError
 */
struct getError
{
	int in0;
};

/**
 *	LIST: getError_List
 */
struct getError_List
{
	struct getError* value;
	struct getError_List* next;
};


struct getError* getError_Create();
void getError_Free(struct getError* obj);
void getError_Sax_Serialize(struct getError* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct getError* getError_Deserialize(xmlNodePtr xmlRoot);
#endif

void getError_Set_in0(struct getError* obj, int in0);
int getError_Get_in0(struct getError* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
