/** Generated by xsd2c*/
#ifndef __getErrorResponse_H__
#define __getErrorResponse_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_GETERRORRESPONSE(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: getErrorResponse
 */
struct getErrorResponse
{
	char* out;
};

/**
 *	LIST: getErrorResponse_List
 */
struct getErrorResponse_List
{
	struct getErrorResponse* value;
	struct getErrorResponse_List* next;
};


struct getErrorResponse* getErrorResponse_Create();
void getErrorResponse_Free(struct getErrorResponse* obj);
void getErrorResponse_Sax_Serialize(struct getErrorResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct getErrorResponse* getErrorResponse_Deserialize(xmlNodePtr xmlRoot);
#endif

void getErrorResponse_Set_out(struct getErrorResponse* obj, const char* out);
char* getErrorResponse_Get_out(struct getErrorResponse* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
