/** Generated by xsd2c */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "getErrorResponse.h"


struct getErrorResponse* getErrorResponse_Create()
{
	struct getErrorResponse* _res;
	_res = (struct getErrorResponse*)malloc(sizeof(struct getErrorResponse));

	_res->out = NULL;

	return _res;
}

void getErrorResponse_Free(struct getErrorResponse* obj)
{
	if (obj == NULL) return;
	if (obj->out != NULL) 
	{
		free(obj->out);
		obj->out = NULL;
	}
	free(obj);
}

void getErrorResponse_Sax_Serialize(struct getErrorResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData)
{
	int attrCount, curCount;
	char **keys;
	char **values;
	char buffer[255];


	attrCount = 0;

	keys = (char**)malloc(sizeof(char*)*attrCount);
	values = (char**)malloc(sizeof(char*)*attrCount);

	curCount = 0;


	OnStartElement(root_element_name, attrCount, keys, values, userData);

	OnStartElement("out", 0, NULL, NULL, userData);
	if (obj->out != NULL)
		OnCharacters("out", obj->out, userData);
	OnEndElement("out", userData);

	OnEndElement(root_element_name, userData);
}

#ifndef _DESERIALIZER_DISABLED_

struct getErrorResponse* getErrorResponse_Deserialize(xmlNodePtr xmlRoot)
{
	xmlNodePtr cur;
	xmlChar *key;
	struct getErrorResponse* obj;
	obj = getErrorResponse_Create();
	cur = xmlRoot->xmlChildrenNode;
	while (cur != NULL) {
		if (cur->type != XML_ELEMENT_NODE) {
			cur = cur->next;
			continue;
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"out"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			getErrorResponse_Set_out(obj, (const char*)key);
			/*xmlFree(key);*/
		}
	// TODO: 
		cur = cur->next;
	}
	return obj;
}

#endif
char* getErrorResponse_Get_out(struct getErrorResponse* obj)
{
	return obj->out;
}

void getErrorResponse_Set_out(struct getErrorResponse* obj, const char* out)
{
	if (obj->out != NULL) free(obj->out);
	obj->out = (char*)malloc(strlen(out)+1);
	strcpy(obj->out, out);
}

