/** Generated by xsd2c */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "setSpecFile.h"


struct setSpecFile* setSpecFile_Create()
{
	struct setSpecFile* _res;
	_res = (struct setSpecFile*)malloc(sizeof(struct setSpecFile));

	_res->in0 = NULL;
	_res->in1 = NULL;

	return _res;
}

void setSpecFile_Free(struct setSpecFile* obj)
{
	if (obj == NULL) return;
	if (obj->in0 != NULL) 
	{
		free(obj->in0);
		obj->in0 = NULL;
	}
	if (obj->in1 != NULL) 
	{
		free(obj->in1);
		obj->in1 = NULL;
	}
	free(obj);
}

void setSpecFile_Sax_Serialize(struct setSpecFile* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData)
{
	int attrCount, curCount;
	char **keys;
	char **values;
	char buffer[255];


	attrCount = 0;

	keys = (char**)malloc(sizeof(char*)*attrCount);
	values = (char**)malloc(sizeof(char*)*attrCount);

	curCount = 0;


	OnStartElement(root_element_name, attrCount, keys, values, userData);

	OnStartElement("in0", 0, NULL, NULL, userData);
	if (obj->in0 != NULL)
		OnCharacters("in0", obj->in0, userData);
	OnEndElement("in0", userData);

	OnStartElement("in1", 0, NULL, NULL, userData);
	if (obj->in1 != NULL)
		OnCharacters("in1", obj->in1, userData);
	OnEndElement("in1", userData);

	OnEndElement(root_element_name, userData);
}

#ifndef _DESERIALIZER_DISABLED_

struct setSpecFile* setSpecFile_Deserialize(xmlNodePtr xmlRoot)
{
	xmlNodePtr cur;
	xmlChar *key;
	struct setSpecFile* obj;
	obj = setSpecFile_Create();
	cur = xmlRoot->xmlChildrenNode;
	while (cur != NULL) {
		if (cur->type != XML_ELEMENT_NODE) {
			cur = cur->next;
			continue;
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"in0"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			setSpecFile_Set_in0(obj, (const char*)key);
			/*xmlFree(key);*/
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"in1"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			setSpecFile_Set_in1(obj, (const char*)key);
			/*xmlFree(key);*/
		}
	// TODO: 
		cur = cur->next;
	}
	return obj;
}

#endif
char* setSpecFile_Get_in0(struct setSpecFile* obj)
{
	return obj->in0;
}

char* setSpecFile_Get_in1(struct setSpecFile* obj)
{
	return obj->in1;
}

void setSpecFile_Set_in0(struct setSpecFile* obj, const char* in0)
{
	if (obj->in0 != NULL) free(obj->in0);
	obj->in0 = (char*)malloc(strlen(in0)+1);
	strcpy(obj->in0, in0);
}

void setSpecFile_Set_in1(struct setSpecFile* obj, const char* in1)
{
	if (obj->in1 != NULL) free(obj->in1);
	obj->in1 = (char*)malloc(strlen(in1)+1);
	strcpy(obj->in1, in1);
}

