/** Generated by xsd2c */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "setSpecFileResponse.h"


struct setSpecFileResponse* setSpecFileResponse_Create()
{
	struct setSpecFileResponse* _res;
	_res = (struct setSpecFileResponse*)malloc(sizeof(struct setSpecFileResponse));

	_res->out = 0;

	return _res;
}

void setSpecFileResponse_Free(struct setSpecFileResponse* obj)
{
	if (obj == NULL) return;
	free(obj);
}

void setSpecFileResponse_Sax_Serialize(struct setSpecFileResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData)
{
	int attrCount, curCount;
	char **keys;
	char **values;
	char buffer[255];


	attrCount = 0;

	keys = (char**)malloc(sizeof(char*)*attrCount);
	values = (char**)malloc(sizeof(char*)*attrCount);

	curCount = 0;


	OnStartElement(root_element_name, attrCount, keys, values, userData);

	OnStartElement("out", 0, NULL, NULL, userData);
	sprintf(buffer, "%d", obj->out);
	OnCharacters("out", buffer, userData);
	OnEndElement("out", userData);

	OnEndElement(root_element_name, userData);
}

#ifndef _DESERIALIZER_DISABLED_

struct setSpecFileResponse* setSpecFileResponse_Deserialize(xmlNodePtr xmlRoot)
{
	xmlNodePtr cur;
	xmlChar *key;
	struct setSpecFileResponse* obj;
	obj = setSpecFileResponse_Create();
	cur = xmlRoot->xmlChildrenNode;
	while (cur != NULL) {
		if (cur->type != XML_ELEMENT_NODE) {
			cur = cur->next;
			continue;
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"out"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			setSpecFileResponse_Set_out(obj, atoi((const char*)key));
			/*xmlFree(key);*/
		}
	// TODO: 
		cur = cur->next;
	}
	return obj;
}

#endif
int setSpecFileResponse_Get_out(struct setSpecFileResponse* obj)
{
	return obj->out;
}

void setSpecFileResponse_Set_out(struct setSpecFileResponse* obj, int out)
{
	obj->out = out;
}

