/** Generated by xsd2c*/
#ifndef __setSourceFileResponse_H__
#define __setSourceFileResponse_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_SETSOURCEFILERESPONSE(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: setSourceFileResponse
 */
struct setSourceFileResponse
{
	int out;
};

/**
 *	LIST: setSourceFileResponse_List
 */
struct setSourceFileResponse_List
{
	struct setSourceFileResponse* value;
	struct setSourceFileResponse_List* next;
};


struct setSourceFileResponse* setSourceFileResponse_Create();
void setSourceFileResponse_Free(struct setSourceFileResponse* obj);
void setSourceFileResponse_Sax_Serialize(struct setSourceFileResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct setSourceFileResponse* setSourceFileResponse_Deserialize(xmlNodePtr xmlRoot);
#endif

void setSourceFileResponse_Set_out(struct setSourceFileResponse* obj, int out);
int setSourceFileResponse_Get_out(struct setSourceFileResponse* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
