/** Generated by xsd2c*/
#ifndef __setSpecFileResponse_H__
#define __setSpecFileResponse_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_SETSPECFILERESPONSE(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: setSpecFileResponse
 */
struct setSpecFileResponse
{
	int out;
};

/**
 *	LIST: setSpecFileResponse_List
 */
struct setSpecFileResponse_List
{
	struct setSpecFileResponse* value;
	struct setSpecFileResponse_List* next;
};


struct setSpecFileResponse* setSpecFileResponse_Create();
void setSpecFileResponse_Free(struct setSpecFileResponse* obj);
void setSpecFileResponse_Sax_Serialize(struct setSpecFileResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct setSpecFileResponse* setSpecFileResponse_Deserialize(xmlNodePtr xmlRoot);
#endif

void setSpecFileResponse_Set_out(struct setSpecFileResponse* obj, int out);
int setSpecFileResponse_Get_out(struct setSpecFileResponse* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
