/** Generated by xsd2c */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "setSourceFileResponse.h"


struct setSourceFileResponse* setSourceFileResponse_Create()
{
	struct setSourceFileResponse* _res;
	_res = (struct setSourceFileResponse*)malloc(sizeof(struct setSourceFileResponse));

	_res->out = 0;

	return _res;
}

void setSourceFileResponse_Free(struct setSourceFileResponse* obj)
{
	if (obj == NULL) return;
	free(obj);
}

void setSourceFileResponse_Sax_Serialize(struct setSourceFileResponse* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData)
{
	int attrCount, curCount;
	char **keys;
	char **values;
	char buffer[255];


	attrCount = 0;

	keys = (char**)malloc(sizeof(char*)*attrCount);
	values = (char**)malloc(sizeof(char*)*attrCount);

	curCount = 0;


	OnStartElement(root_element_name, attrCount, keys, values, userData);

	OnStartElement("out", 0, NULL, NULL, userData);
	sprintf(buffer, "%d", obj->out);
	OnCharacters("out", buffer, userData);
	OnEndElement("out", userData);

	OnEndElement(root_element_name, userData);
}

#ifndef _DESERIALIZER_DISABLED_

struct setSourceFileResponse* setSourceFileResponse_Deserialize(xmlNodePtr xmlRoot)
{
	xmlNodePtr cur;
	xmlChar *key;
	struct setSourceFileResponse* obj;
	obj = setSourceFileResponse_Create();
	cur = xmlRoot->xmlChildrenNode;
	while (cur != NULL) {
		if (cur->type != XML_ELEMENT_NODE) {
			cur = cur->next;
			continue;
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"out"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			setSourceFileResponse_Set_out(obj, atoi((const char*)key));
			/*xmlFree(key);*/
		}
	// TODO: 
		cur = cur->next;
	}
	return obj;
}

#endif
int setSourceFileResponse_Get_out(struct setSourceFileResponse* obj)
{
	return obj->out;
}

void setSourceFileResponse_Set_out(struct setSourceFileResponse* obj, int out)
{
	obj->out = out;
}

