/** Generated by xsd2c*/
#ifndef __setSourceFile_H__
#define __setSourceFile_H__



#ifndef _DESERIALIZER_DISABLE_
	#include <libxml/parser.h>
#endif


#define TO_SETSOURCEFILE(derived) (derived->__base) 


#ifdef __cplusplus
extern "C" {
#endif 


/**
 *	OBJECT: setSourceFile
 */
struct setSourceFile
{
	char* in0;
};

/**
 *	LIST: setSourceFile_List
 */
struct setSourceFile_List
{
	struct setSourceFile* value;
	struct setSourceFile_List* next;
};


struct setSourceFile* setSourceFile_Create();
void setSourceFile_Free(struct setSourceFile* obj);
void setSourceFile_Sax_Serialize(struct setSourceFile* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData);

#ifndef _DESERIALIZER_DISABLE_
struct setSourceFile* setSourceFile_Deserialize(xmlNodePtr xmlRoot);
#endif

void setSourceFile_Set_in0(struct setSourceFile* obj, const char* in0);
char* setSourceFile_Get_in0(struct setSourceFile* obj);


#ifdef __cplusplus
};
#endif /*__cplusplus*/



#endif
