/** Generated by xsd2c */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "setSourceFile.h"


struct setSourceFile* setSourceFile_Create()
{
	struct setSourceFile* _res;
	_res = (struct setSourceFile*)malloc(sizeof(struct setSourceFile));

	_res->in0 = NULL;
	_res->in1 = NULL;

	return _res;
}

void setSourceFile_Free(struct setSourceFile* obj)
{
	if (obj == NULL) return;
	if (obj->in0 != NULL) 
	{
		free(obj->in0);
		obj->in0 = NULL;
	}
	free(obj);
}

void setSourceFile_Sax_Serialize(struct setSourceFile* obj,
		 const char *root_element_name,
		 void (*OnStartElement)(const char* element_name, int attr_count, char **keys, char **values, void* userData),
		 void (*OnCharacters)(const char* element_name, const char* chars, void* userData),
		 void (*OnEndElement)(const char* element_name, void* userData),
		 void* userData)
{
	int attrCount, curCount;
	char **keys;
	char **values;
	char buffer[255];


	attrCount = 0;

	keys = (char**)malloc(sizeof(char*)*attrCount);
	values = (char**)malloc(sizeof(char*)*attrCount);

	curCount = 0;


	OnStartElement(root_element_name, attrCount, keys, values, userData);

	OnStartElement("in0", 0, NULL, NULL, userData);
	if (obj->in0 != NULL)
		OnCharacters("in0", obj->in0, userData);
	OnEndElement("in0", userData);
	if (obj->in1)
	base64Binary_Sax_Serialize(obj->in1, "in1", OnStartElement, OnCharacters, OnEndElement, userData);

	OnEndElement(root_element_name, userData);
}

#ifndef _DESERIALIZER_DISABLED_

struct setSourceFile* setSourceFile_Deserialize(xmlNodePtr xmlRoot)
{
	xmlNodePtr cur;
	xmlChar *key;
	struct setSourceFile* obj;
	obj = setSourceFile_Create();
	cur = xmlRoot->xmlChildrenNode;
	while (cur != NULL) {
		if (cur->type != XML_ELEMENT_NODE) {
			cur = cur->next;
			continue;
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"in0"))){
			key = xmlNodeListGetString(cur->doc, cur->xmlChildrenNode, 1);
			setSourceFile_Set_in0(obj, (const char*)key);
			/*xmlFree(key);*/
		}
		if ((!xmlStrcmp(cur->name, (const xmlChar *)"in1"))){
			setSourceFile_Set_in1( obj, base64Binary_Deserialize(cur) );
		}
	// TODO: 
		cur = cur->next;
	}
	return obj;
}

#endif
char* setSourceFile_Get_in0(struct setSourceFile* obj)
{
	return obj->in0;
}

void setSourceFile_Set_in0(struct setSourceFile* obj, const char* in0)
{
	if (obj->in0 != NULL) free(obj->in0);
	obj->in0 = (char*)malloc(strlen(in0)+1);
	strcpy(obj->in0, in0);
}

